--- #YAML:1.0
name:               URI-GoogleChart
version:            1.02
abstract:           Generate Google Chart URIs
author:
    - Gisle Aas <gisle@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    perl:  5.006
    URI:   1
resources:
    repository:  http://github.com/gisle/uri-googlechart
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.4801
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    LWP:  0
